/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

// ActiveMQArtemisListerExpansion allows custom methods to be added to
// ActiveMQArtemisLister.
type ActiveMQArtemisListerExpansion interface{}

// ActiveMQArtemisNamespaceListerExpansion allows custom methods to be added to
// ActiveMQArtemisNamespaceLister.
type ActiveMQArtemisNamespaceListerExpansion interface{}

// ActiveMQArtemisAddressListerExpansion allows custom methods to be added to
// ActiveMQArtemisAddressLister.
type ActiveMQArtemisAddressListerExpansion interface{}

// ActiveMQArtemisAddressNamespaceListerExpansion allows custom methods to be added to
// ActiveMQArtemisAddressNamespaceLister.
type ActiveMQArtemisAddressNamespaceListerExpansion interface{}

// ActiveMQArtemisScaledownListerExpansion allows custom methods to be added to
// ActiveMQArtemisScaledownLister.
type ActiveMQArtemisScaledownListerExpansion interface{}

// ActiveMQArtemisScaledownNamespaceListerExpansion allows custom methods to be added to
// ActiveMQArtemisScaledownNamespaceLister.
type ActiveMQArtemisScaledownNamespaceListerExpansion interface{}
