apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  acceptors:
  - name: ssl
    port: 61618
    protocols: all
    sslEnabled: true
    sslSecret: ssl-acceptor-ssl-secret
  deploymentPlan:
    extraMounts:
      secrets:
      - amq-ssl-secret
      configMaps:
      - ca-bundle