/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"time"

	v2alpha1 "github.com/rh-messaging/activemq-artemis-operator/pkg/apis/broker/v2alpha1"
	scheme "github.com/rh-messaging/activemq-artemis-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ActiveMQArtemisScaledownStatusesGetter has a method to return a ActiveMQArtemisScaledownStatusInterface.
// A group's client should implement this interface.
type ActiveMQArtemisScaledownStatusesGetter interface {
	ActiveMQArtemisScaledownStatuses(namespace string) ActiveMQArtemisScaledownStatusInterface
}

// ActiveMQArtemisScaledownStatusInterface has methods to work with ActiveMQArtemisScaledownStatus resources.
type ActiveMQArtemisScaledownStatusInterface interface {
	Create(*v2alpha1.ActiveMQArtemisScaledownStatus) (*v2alpha1.ActiveMQArtemisScaledownStatus, error)
	Update(*v2alpha1.ActiveMQArtemisScaledownStatus) (*v2alpha1.ActiveMQArtemisScaledownStatus, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v2alpha1.ActiveMQArtemisScaledownStatus, error)
	List(opts v1.ListOptions) (*v2alpha1.ActiveMQArtemisScaledownStatusList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v2alpha1.ActiveMQArtemisScaledownStatus, err error)
	ActiveMQArtemisScaledownStatusExpansion
}

// activeMQArtemisScaledownStatuses implements ActiveMQArtemisScaledownStatusInterface
type activeMQArtemisScaledownStatuses struct {
	client rest.Interface
	ns     string
}

// newActiveMQArtemisScaledownStatuses returns a ActiveMQArtemisScaledownStatuses
func newActiveMQArtemisScaledownStatuses(c *BrokerV2alpha1Client, namespace string) *activeMQArtemisScaledownStatuses {
	return &activeMQArtemisScaledownStatuses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the activeMQArtemisScaledownStatus, and returns the corresponding activeMQArtemisScaledownStatus object, and an error if there is any.
func (c *activeMQArtemisScaledownStatuses) Get(name string, options v1.GetOptions) (result *v2alpha1.ActiveMQArtemisScaledownStatus, err error) {
	result = &v2alpha1.ActiveMQArtemisScaledownStatus{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("activemqartemisscaledownstatuses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ActiveMQArtemisScaledownStatuses that match those selectors.
func (c *activeMQArtemisScaledownStatuses) List(opts v1.ListOptions) (result *v2alpha1.ActiveMQArtemisScaledownStatusList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.ActiveMQArtemisScaledownStatusList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("activemqartemisscaledownstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested activeMQArtemisScaledownStatuses.
func (c *activeMQArtemisScaledownStatuses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("activemqartemisscaledownstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a activeMQArtemisScaledownStatus and creates it.  Returns the server's representation of the activeMQArtemisScaledownStatus, and an error, if there is any.
func (c *activeMQArtemisScaledownStatuses) Create(activeMQArtemisScaledownStatus *v2alpha1.ActiveMQArtemisScaledownStatus) (result *v2alpha1.ActiveMQArtemisScaledownStatus, err error) {
	result = &v2alpha1.ActiveMQArtemisScaledownStatus{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("activemqartemisscaledownstatuses").
		Body(activeMQArtemisScaledownStatus).
		Do().
		Into(result)
	return
}

// Update takes the representation of a activeMQArtemisScaledownStatus and updates it. Returns the server's representation of the activeMQArtemisScaledownStatus, and an error, if there is any.
func (c *activeMQArtemisScaledownStatuses) Update(activeMQArtemisScaledownStatus *v2alpha1.ActiveMQArtemisScaledownStatus) (result *v2alpha1.ActiveMQArtemisScaledownStatus, err error) {
	result = &v2alpha1.ActiveMQArtemisScaledownStatus{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("activemqartemisscaledownstatuses").
		Name(activeMQArtemisScaledownStatus.Name).
		Body(activeMQArtemisScaledownStatus).
		Do().
		Into(result)
	return
}

// Delete takes name of the activeMQArtemisScaledownStatus and deletes it. Returns an error if one occurs.
func (c *activeMQArtemisScaledownStatuses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("activemqartemisscaledownstatuses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *activeMQArtemisScaledownStatuses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("activemqartemisscaledownstatuses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched activeMQArtemisScaledownStatus.
func (c *activeMQArtemisScaledownStatuses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v2alpha1.ActiveMQArtemisScaledownStatus, err error) {
	result = &v2alpha1.ActiveMQArtemisScaledownStatus{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("activemqartemisscaledownstatuses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
