/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/rh-messaging/activemq-artemis-operator/pkg/apis/broker/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeActiveMQArtemisScaledownStatuses implements ActiveMQArtemisScaledownStatusInterface
type FakeActiveMQArtemisScaledownStatuses struct {
	Fake *FakeBrokerV2alpha1
	ns   string
}

var activemqartemisscaledownstatusesResource = schema.GroupVersionResource{Group: "broker.amq.io", Version: "v2alpha1", Resource: "activemqartemisscaledownstatuses"}

var activemqartemisscaledownstatusesKind = schema.GroupVersionKind{Group: "broker.amq.io", Version: "v2alpha1", Kind: "ActiveMQArtemisScaledownStatus"}

// Get takes name of the activeMQArtemisScaledownStatus, and returns the corresponding activeMQArtemisScaledownStatus object, and an error if there is any.
func (c *FakeActiveMQArtemisScaledownStatuses) Get(name string, options v1.GetOptions) (result *v2alpha1.ActiveMQArtemisScaledownStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(activemqartemisscaledownstatusesResource, c.ns, name), &v2alpha1.ActiveMQArtemisScaledownStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ActiveMQArtemisScaledownStatus), err
}

// List takes label and field selectors, and returns the list of ActiveMQArtemisScaledownStatuses that match those selectors.
func (c *FakeActiveMQArtemisScaledownStatuses) List(opts v1.ListOptions) (result *v2alpha1.ActiveMQArtemisScaledownStatusList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(activemqartemisscaledownstatusesResource, activemqartemisscaledownstatusesKind, c.ns, opts), &v2alpha1.ActiveMQArtemisScaledownStatusList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ActiveMQArtemisScaledownStatusList), err
}

// Watch returns a watch.Interface that watches the requested activeMQArtemisScaledownStatuses.
func (c *FakeActiveMQArtemisScaledownStatuses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(activemqartemisscaledownstatusesResource, c.ns, opts))

}

// Create takes the representation of a activeMQArtemisScaledownStatus and creates it.  Returns the server's representation of the activeMQArtemisScaledownStatus, and an error, if there is any.
func (c *FakeActiveMQArtemisScaledownStatuses) Create(activeMQArtemisScaledownStatus *v2alpha1.ActiveMQArtemisScaledownStatus) (result *v2alpha1.ActiveMQArtemisScaledownStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(activemqartemisscaledownstatusesResource, c.ns, activeMQArtemisScaledownStatus), &v2alpha1.ActiveMQArtemisScaledownStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ActiveMQArtemisScaledownStatus), err
}

// Update takes the representation of a activeMQArtemisScaledownStatus and updates it. Returns the server's representation of the activeMQArtemisScaledownStatus, and an error, if there is any.
func (c *FakeActiveMQArtemisScaledownStatuses) Update(activeMQArtemisScaledownStatus *v2alpha1.ActiveMQArtemisScaledownStatus) (result *v2alpha1.ActiveMQArtemisScaledownStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(activemqartemisscaledownstatusesResource, c.ns, activeMQArtemisScaledownStatus), &v2alpha1.ActiveMQArtemisScaledownStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ActiveMQArtemisScaledownStatus), err
}

// Delete takes name of the activeMQArtemisScaledownStatus and deletes it. Returns an error if one occurs.
func (c *FakeActiveMQArtemisScaledownStatuses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(activemqartemisscaledownstatusesResource, c.ns, name), &v2alpha1.ActiveMQArtemisScaledownStatus{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeActiveMQArtemisScaledownStatuses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(activemqartemisscaledownstatusesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v2alpha1.ActiveMQArtemisScaledownStatusList{})
	return err
}

// Patch applies the patch and returns the patched activeMQArtemisScaledownStatus.
func (c *FakeActiveMQArtemisScaledownStatuses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v2alpha1.ActiveMQArtemisScaledownStatus, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(activemqartemisscaledownstatusesResource, c.ns, name, pt, data, subresources...), &v2alpha1.ActiveMQArtemisScaledownStatus{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.ActiveMQArtemisScaledownStatus), err
}
