// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v2alpha4

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemis":                schema_pkg_apis_broker_v2alpha4_ActiveMQArtemis(ref),
		"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisAddress":         schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisAddress(ref),
		"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisAddressSpec":     schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisAddressSpec(ref),
		"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisAddressStatus":   schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisAddressStatus(ref),
		"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisScaledown":       schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisScaledown(ref),
		"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisScaledownSpec":   schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisScaledownSpec(ref),
		"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisScaledownStatus": schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisScaledownStatus(ref),
		"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisSpec":            schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisSpec(ref),
		"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisStatus":          schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisStatus(ref),
	}
}

func schema_pkg_apis_broker_v2alpha4_ActiveMQArtemis(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemis is the Schema for the activemqartemis API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisSpec", "github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisAddress(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisAddress is the Schema for the activemqartemisaddresses API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisAddressSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisAddressStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisAddressSpec", "github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisAddressStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisAddressSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisAddressSpec defines the desired state of ActiveMQArtemisAddress",
				Properties: map[string]spec.Schema{
					"addressName": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"queueName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"routingType": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"removeFromBrokerOnDelete": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
				},
				Required: []string{"addressName", "queueName", "routingType"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisAddressStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisAddressStatus defines the observed state of ActiveMQArtemisAddress",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisScaledown(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisScaledown is the Schema for the activemqartemisscaledowns API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisScaledownSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisScaledownStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisScaledownSpec", "github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisScaledownStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisScaledownSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisScaledownSpec defines the desired state of ActiveMQArtemisScaledown",
				Properties: map[string]spec.Schema{
					"localOnly": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html Namespace  string `json:\"namespace\"`",
							Type:        []string{"boolean"},
							Format:      "",
						},
					},
				},
				Required: []string{"localOnly"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisScaledownStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisScaledownStatus defines the observed state of ActiveMQArtemisScaledown",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisSpec defines the desired state of ActiveMQArtemis",
				Properties: map[string]spec.Schema{
					"adminUser": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"adminPassword": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"deploymentPlan": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.DeploymentPlanType"),
						},
					},
					"acceptors": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.AcceptorType"),
									},
								},
							},
						},
					},
					"connectors": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ConnectorType"),
									},
								},
							},
						},
					},
					"console": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ConsoleType"),
						},
					},
					"storage": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.StorageType"),
						},
					},
					"version": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"upgrades": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisUpgrades"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.AcceptorType", "github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ActiveMQArtemisUpgrades", "github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ConnectorType", "github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.ConsoleType", "github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.StorageType","github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v2alpha4.DeploymentPlanType"},
	}
}

func schema_pkg_apis_broker_v2alpha4_ActiveMQArtemisStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActiveMQArtemisStatus defines the observed state of ActiveMQArtemis",
				Properties: map[string]spec.Schema{
					"podStatus": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html",
							Ref:         ref("github.com/RHsyseng/operator-utils/pkg/olm.DeploymentStatus"),
						},
					},
				},
				Required: []string{"podStatus"},
			},
		},
		Dependencies: []string{
			"github.com/RHsyseng/operator-utils/pkg/olm.DeploymentStatus"},
	}
}
